### PR TITLE
Add ability to use a function for the `lookup` option.

### LINKED ISSUE #12: Variable Rate Limit
The `lookup` right now is set to an array of values. This is useful, but is always AND not OR. What if I wanted to rate limit by an api key if available and valid, or fallback to an ip? This could potentially use a function instead of an array, that took in the request.

What if falling back to an ip would change how many requests they could make in `total`? I suppose the function above could also pass in the config of the express limiter.

I'd be happy to make a pr once these concepts have been approved.

### PR DESCRIPTION
**Pull request by blainesch**
Fixes #12

### CODE REVIEW

**Comment by fizerkhan** [comment]
@ded Can you please merge it?

**Comment by lushc** [comment]
+1

**Comment by cjthompson** [comment]
I merged this PR into my fork at https://github.com/cjthompson/express-limiter .

**Comment by ded** [comment]
hi @blainesch @fizerkhan @lushc is this something you'd still like to get merged. i was looking at the PR and all seems fine. For some reason this one skipped passed my radar, but I'd like to get it in. At this point it doesn't merge (due to time passing), but if you're up to fixing the conflicts, it would be great to get it back in

**Comment by ded** [comment]
cc @cjthompson

**Comment by blainesch** [comment]
@ded updated.

**Comment by ded** [comment]
:+1: @blainesch

**Comment by blainesch** [comment]
w00t

**Pull request merged**
